/*
###################################################################################################
Título: Imprimindo/exibindo variáveis
---------------------------------------------------------------------------------------------------
Este exercício ajuda a praticar a manipulação de variáveis no acesso de valores e imprimir no console.
###################################################################################################
*/

// Declarando Variável nome
const nome = "Fulana"
// Declarando Variável idade
const idade = 21

//Imprimindo / exibindo no console
console.log("Olá!", "Meu nome é ", nome, "e eu tenho", idade, "anos")
// Olá! Meu nome é Fulana e eu tenho 21 anos
